generic connector with code review changes
wso2-extensions/identity-outbound-auth-oauth2 pull request #2
Opened 2020-07-09 23:08 UTC by krishnilak

## Purpose
> Fixing issues (which is clearly decided) in previous PR

2020-07-10 05:05 UTC, GDRDABARERA requested changes

2020-07-10 05:05 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/pom.xml
> +        <version>1.0-SNAPSHOT</version>
1.0.0-SNAPSHOT

2020-07-10 05:05 UTC, GDRDABARERA commented on pom.xml
> +</project>
new line

2020-07-10 05:05 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/pom.xml
> +</project>
new line

2020-07-10 05:05 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/src/main/java/org.wso2.carbon.identity.application.authenticator.oauth2/Oauth2GenericAuthenticator.java
> +/* Oauth2GenericAuthenticator supports federating authentication with External Oauth IDP s from WSO2 IAM */
put correct class level comments

2020-07-14 17:29 UTC, GDRDABARERA requested changes

2020-07-14 17:29 UTC, GDRDABARERA commented on .idea/.name
> +identity-outbound-oauth-oauth2
Can we remove these files

2020-07-14 17:29 UTC, GDRDABARERA commented on .idea/.gitignore
> +/workspace.xml
Can we remove these files

2020-07-14 17:29 UTC, GDRDABARERA commented on .idea/compiler.xml
> +</project>
remove .idea files

2020-07-14 17:29 UTC, GDRDABARERA commented on .idea/encodings.xml
> +</project>
Remove these .idea files

2020-07-15 02:49 UTC, GDRDABARERA requested changes

2020-07-15 02:49 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/src/main/java/org.wso2.carbon.identity.application.authenticator.oauth2/Oauth2GenericAuthenticator.java
> +
Remove line space

2020-07-15 02:49 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/src/main/java/org.wso2.carbon.identity.application.authenticator.oauth2/Oauth2GenericAuthenticator.java
> +                logger.debug("authzRequest");
Join this two comments to one

2020-07-15 02:49 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/src/main/java/org.wso2.carbon.identity.application.authenticator.oauth2/Oauth2GenericAuthenticator.java
> +
Remove space
space

2020-07-15 02:49 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/src/main/java/org.wso2.carbon.identity.application.authenticator.oauth2/Oauth2GenericAuthenticator.java
> +
Remove line space and format

2020-07-15 02:49 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/src/main/java/org.wso2.carbon.identity.application.authenticator.oauth2/Oauth2GenericAuthenticator.java
> +
Remove line space

2020-07-15 02:49 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/src/main/java/org.wso2.carbon.identity.application.authenticator.oauth2/Oauth2GenericAuthenticator.java
> +            if (subjectFromClaims != null && !subjectFromClaims.isEmpty()) {
Shall we use StringUtils.isBlank it checks for both null and empty

2020-07-15 02:49 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/src/main/java/org.wso2.carbon.identity.application.authenticator.oauth2/Oauth2GenericAuthenticator.java
> +            logger.info(tokenResponseStr);
Is it okay to log this as info, does this has sensitive infor, make this audit

2020-07-15 02:49 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/src/main/java/org.wso2.carbon.identity.application.authenticator.oauth2/Oauth2GenericAuthenticator.java
> + * Oauth2GenericAuthenticator supports federating authentication with External Oauth IDP s from WSO2 IAM
Put a fullstop after the comment

2020-07-15 02:49 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/src/main/java/org.wso2.carbon.identity.application.authenticator.oauth2/Oauth2GenericAuthenticator.java
> +        implements FederatedApplicationAuthenticator {
Add enough audit logs to all the classes

2020-07-15 02:49 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/src/main/java/org.wso2.carbon.identity.application.authenticator.oauth2/Oauth2GenericAuthenticator.java
> +
Remove line

2020-07-15 02:49 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/src/main/java/org.wso2.carbon.identity.application.authenticator.oauth2/Oauth2GenericAuthenticator.java
> +                        .setParameter("state", state).buildQueryMessage();
Put "state" to a constant and "code" too

2020-07-15 02:49 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/src/main/java/org.wso2.carbon.identity.application.authenticator.oauth2/Oauth2GenericAuthenticator.java
> +                String base64EncodedCredential = new String(Base64.encodeBase64((clientId + ":" +
Use constants for all hard coded values

2020-07-15 02:49 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/src/main/java/org.wso2.carbon.identity.application.authenticator.oauth2/Oauth2GenericAuthenticator.java
> +            return state.split(",")[0];
Can this throw a arrayIndexOitofbound

2020-07-15 02:49 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/src/main/java/org.wso2.carbon.identity.application.authenticator.oauth2/Oauth2GenericAuthenticator.java
> +            this.tokenEndpoint = getAuthenticatorConfig().getParameterMap()
Do not write inline if conditions. Not recommended as they are not readable

2020-07-15 12:08 UTC, krishnilak commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/src/main/java/org.wso2.carbon.identity.application.authenticator.oauth2/Oauth2GenericAuthenticator.java
> +            return state.split(",")[0];
I added a seperate catch

2020-07-16 04:50 UTC, GDRDABARERA commented on components/org.wso2.carbon.identity.application.authenticator.oauth2/src/main/java/org.wso2.carbon.identity.application.authenticator.oauth2/Oauth2GenericAuthenticator.java
> +                logger.debug(String.join("Authorization Request",authzRequest.getLocationUri()));
Authorization Request: ",authzRequest.getLocationUri()

2020-07-16 04:53 UTC, GDRDABARERA approved these changes

2020-07-16 05:06 UTC, merged